### PR TITLE
Update Symfony Process() usage

### PR DESCRIPTION
**Pull request by dwoods**

### CODE REVIEW

**Comment by dwoods** [comment]
Fixes #10

**Comment by bbenesh** [comment]
I tested this locally and it fixed my issues with `lando pull` on a D10 site.

**Comment by bbenesh** [comment]
I checked the original commit with my local D9 demo and it worked!

**Comment by tobybellwood** [comment]
Just reviewing this now, and it no longer works (with our test instance, running ssh portal/token) - will look into it

```
cli-drupal:/app$ drush la

In RequestException.php line 113:
                                                                                                                        
  Client error: `POST https://api.main.lagoon-core.test6.amazee.io/graphql` resulted in a `401 Unauthorized` response:  
  {"errors":[{"message":"Unauthorized - Bearer token required"}]}    
  ```

**Comment by tobybellwood** [comment]
I"m going to merge this, then PR the SSH Portal fix (it's a bit picker about commands, and doesn't like being passed the token and the 2&>1 redirect, so I'll handle errors in the mustRun

**Pull request merged**
